openapi: 3.0.3
info:
  title: RaceLab Ingestion API
  description: |
    Data Platform Phase 1 - Ingestion API Contracts
    
    이 API는 데이터 수집 파이프라인의 내부 엔드포인트를 정의합니다.
    주로 Cron Jobs, Workers, 관리자 도구에서 호출됩니다.
  version: 1.0.0
  contact:
    name: RaceLab Team

servers:
  - url: https://racelab.kr/api
    description: Production
  - url: http://localhost:3000/api
    description: Development

tags:
  - name: Ingestion
    description: 데이터 수집 관련 엔드포인트
  - name: Status
    description: 수집 현황 조회

paths:
  /ingestion/trigger/schedules:
    post:
      summary: Trigger schedule collection
      description: |
        당일 경주 일정을 KRA/KSPO API에서 수집합니다.
        일반적으로 Vercel Cron에서 매일 06:00에 호출됩니다.
      tags:
        - Ingestion
      security:
        - ApiKeyAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                  description: 수집할 날짜 (기본값: 오늘)
                  example: "2024-12-10"
                raceTypes:
                  type: array
                  items:
                    type: string
                    enum: [horse, cycle, boat]
                  description: 수집할 종목 (기본값: 전체)
      responses:
        '200':
          description: 수집 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /ingestion/trigger/entries:
    post:
      summary: Trigger entries collection
      description: |
        특정 경주의 출주표를 수집합니다.
        경주 시작 2시간 전에 자동 트리거됩니다.
      tags:
        - Ingestion
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - raceIds
              properties:
                raceIds:
                  type: array
                  items:
                    type: string
                  description: 수집할 경주 ID 목록
                  example: ["horse-seoul-1-20241210", "horse-seoul-2-20241210"]
      responses:
        '200':
          description: 수집 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /ingestion/trigger/odds:
    post:
      summary: Trigger odds collection
      description: |
        특정 경주의 현재 배당률을 수집합니다.
        경주 시작 전 1분 간격으로 호출됩니다.
      tags:
        - Ingestion
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - raceIds
              properties:
                raceIds:
                  type: array
                  items:
                    type: string
                  description: 수집할 경주 ID 목록
      responses:
        '200':
          description: 수집 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OddsIngestionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /ingestion/trigger/results:
    post:
      summary: Trigger results collection
      description: |
        특정 경주의 결과를 수집합니다.
        경주 종료 후 5분에 자동 트리거됩니다.
      tags:
        - Ingestion
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - raceIds
              properties:
                raceIds:
                  type: array
                  items:
                    type: string
                  description: 수집할 경주 ID 목록
      responses:
        '200':
          description: 수집 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /ingestion/status:
    get:
      summary: Get ingestion status
      description: 데이터 수집 현황을 조회합니다.
      tags:
        - Status
      security:
        - ApiKeyAuth: []
      parameters:
        - name: date
          in: query
          schema:
            type: string
            format: date
          description: 조회할 날짜 (기본값: 오늘)
      responses:
        '200':
          description: 현황 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionStatus'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /ingestion/failures:
    get:
      summary: Get ingestion failures
      description: 수집 실패 목록을 조회합니다.
      tags:
        - Status
      security:
        - ApiKeyAuth: []
      parameters:
        - name: resolved
          in: query
          schema:
            type: boolean
          description: 해결 여부 필터
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
          description: 조회 개수
      responses:
        '200':
          description: 실패 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/IngestionFailure'
                  timestamp:
                    type: string
                    format: date-time

  /ingestion/failures/{id}/retry:
    post:
      summary: Retry failed ingestion
      description: 실패한 수집 건을 재시도합니다.
      tags:
        - Ingestion
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 실패 레코드 ID
      responses:
        '200':
          description: 재시도 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '404':
          description: 실패 레코드 없음

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Ingestion-Key
      description: 내부 Ingestion API 키

  schemas:
    IngestionResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            collected:
              type: integer
              description: 수집된 레코드 수
            skipped:
              type: integer
              description: 스킵된 레코드 수
            errors:
              type: integer
              description: 에러 발생 수
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
        timestamp:
          type: string
          format: date-time

    OddsIngestionResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            snapshots:
              type: integer
              description: 저장된 스냅샷 수
            races:
              type: integer
              description: 처리된 경주 수
        timestamp:
          type: string
          format: date-time

    IngestionStatus:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            date:
              type: string
              format: date
            summary:
              type: object
              properties:
                totalRaces:
                  type: integer
                schedulesCollected:
                  type: integer
                entriesCollected:
                  type: integer
                oddsSnapshots:
                  type: integer
                resultsCollected:
                  type: integer
                failureCount:
                  type: integer
            lastCollection:
              type: object
              properties:
                schedules:
                  type: string
                  format: date-time
                entries:
                  type: string
                  format: date-time
                odds:
                  type: string
                  format: date-time
                results:
                  type: string
                  format: date-time
        timestamp:
          type: string
          format: date-time

    IngestionFailure:
      type: object
      properties:
        id:
          type: integer
        source:
          type: string
          enum: [kra, kspo]
        endpoint:
          type: string
        errorMessage:
          type: string
        errorCode:
          type: string
        retryCount:
          type: integer
        maxRetries:
          type: integer
        resolved:
          type: boolean
        resolvedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time

  responses:
    Unauthorized:
      description: 인증 실패
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: UNAUTHORIZED
                  message:
                    type: string
                    example: Invalid or missing API key

    InternalError:
      description: 서버 에러
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_ERROR
                  message:
                    type: string
